version: '2.1'

services:
  mysql:
    extends:
      file: docker-compose.yml
      service: mysql
    mem_limit: 512m
    environment:
      - CONSUL_AGENT=1
      - CONSUL=consul
      - LOG_LEVEL=DEBUG
    links:
      - consul:consul
    ports:
      - 3306

  consul:
    extends:
      file: docker-compose.yml
      service: consul
    ports:
    - 8500:8500
